using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using HumanoidMocap.Cleanup;
using HumanoidMocap.Mapping;
using HumanoidMocap.Maths;
using HumanoidMocap.Motion;
using HumanoidMocap.Target;

namespace HumanoidMocap.Inference;
using Vector3 = System.Numerics.Vector3;

/// <summary>Fits genuinely reconstructed hand landmarks to fixed template bone lengths.
/// Camera-plane wrist placement and shoulder/elbow IK are explicitly derived estimates.</summary>
public sealed class HandMotionBuilder
{
    readonly TargetRig rig;
    readonly ArmConstraintSolver left=new(),right=new();
    readonly XForm[] rest;
    XForm[]? previous;
    public MotionDocument Document { get; }
    public bool SwapHands { get; set; }
    public float WristPlaneWidth { get; set; } = .9f;
    public float WristPlaneDepth { get; set; } = .4f;
    public HandMotionBuilder(TargetRig template,string name,string video,string hash,double fps)
    {
        rig=template;rest=template.Skeleton.RestWorld.Select(t=>new XForm(t.Pos/100,t.Rot)).ToArray();
        Document=new MotionDocument{Name=name,SourceVideo=video,SourceSha256=hash,SourceFps=fps,
            Backend="MediaPipe hands / experimental managed C#",ModelVersion="hand_landmarker/float16/1",
            Space=MotionSpace.CameraRelative,MetricScaleCalibrated=false};
        foreach(var b in rig.Skeleton.Bones)Document.Bones.Add(new(){Name=b.Name,Parent=b.ParentIndex,Role=rig.RoleOf(b.Index),
            Group=rig.RoleOf(b.Index)?.ToString().Contains("Prox")==true||rig.RoleOf(b.Index)?.ToString().Contains("Mid")==true||rig.RoleOf(b.Index)?.ToString().Contains("Dist")==true?"fingers":"arms",
            RestPosition=MotionDocument.A(b.RestLocal.Pos/100),RestRotation=MotionDocument.A(b.RestLocal.Rot)});
        Document.Diagnostics.AddRange(new[]{"Experimental landmark reconstruction, not ACE-Ego-Hand. Model-port parity has not been established.",
            "Hand-relative 3D landmarks are reconstructed. Wrist depth/translation use an editable camera-plane assumption.",
            "Shoulders and elbows are generated by IK. Unobserved joints hold their previous pose and are labeled unobserved.",
            "No world-space recovery, object tracking, or measured per-joint confidence. Inspect handedness before export."});
    }
    public void Add(double time,int width,int height,IReadOnlyList<HandObservation> observations)
    {
        var frame=previous?.ToArray()??rig.Skeleton.Bones.Select(b=>new XForm(b.RestLocal.Pos,b.RestLocal.Rot)).ToArray();
        var world=new XForm[frame.Length];FkUtil.ToWorld(frame,rig.Skeleton,world);
        var evidence=Enumerable.Repeat(JointEvidence.Unobserved,frame.Length).ToArray();
        foreach(var observed in observations.GroupBy(h=>h.Side).Select(g=>g.OrderByDescending(h=>h.Presence).First()))
        {
            var side=SwapHands?(observed.Side=="L"?"R":"L"):observed.Side;
            BoneRole Role(string name)=>Enum.Parse<BoneRole>(name+side);
            if(rig.BoneForRole(Role("UpperArm")) is not int upper||rig.BoneForRole(Role("LowerArm")) is not int lower||rig.BoneForRole(Role("Hand")) is not int hand)continue;
            var points=observed.RelativeWorldLandmarks.Select(v=>new Vector3(-v.X,-v.Y,v.Z)).ToArray();
            var screen=observed.ImageLandmarks[0];var wrist=new Vector3(-((screen.X/width)-.5f)*WristPlaneWidth,1.65f-screen.Y/height*.65f,WristPlaneDepth);
            var sign=side=="L"?1:-1;
            var result=(side=="L"?left:right).Solve(wrist,Quaternion.Identity,new ArmSettings{Shoulder=rest[upper].Pos,
                ElbowTarget=new(sign*.5f,1.1f,.15f),UpperLength=Vector3.Distance(rest[upper].Pos,rest[lower].Pos),ForearmLength=Vector3.Distance(rest[lower].Pos,rest[hand].Pos)});
            var desired=new Dictionary<int,Quaternion>();
            desired[upper]=Quaternion.Normalize(MathQ.FromTo(rest[lower].Pos-rest[upper].Pos,result.Elbow-result.Shoulder)*rest[upper].Rot);
            desired[lower]=Quaternion.Normalize(MathQ.FromTo(rest[hand].Pos-rest[lower].Pos,result.Wrist-result.Elbow)*rest[lower].Rot);
            var index=rig.BoneForRole(Role("IndexProx"));var pinky=rig.BoneForRole(Role("PinkyProx"));var middle=rig.BoneForRole(Role("MiddleProx"));
            if(index is int ib && pinky is int pb && middle is int mb)
            {
                var origin=Basis(rest[mb].Pos-rest[hand].Pos,rest[ib].Pos-rest[pb].Pos);
                var target=Basis(points[9]-points[0],points[5]-points[17]);
                desired[hand]=Quaternion.Normalize(target*Quaternion.Inverse(origin)*rest[hand].Rot);
            }
            evidence[upper]=evidence[lower]=JointEvidence.GeneratedIk;evidence[hand]=JointEvidence.Reconstructed;
            foreach(var (finger,start) in new[]{("Thumb",1),("Index",5),("Middle",9),("Ring",13),("Pinky",17)})
            {
                var segments=new[]{"Prox","Mid","Dist"};
                for(var k=0;k<3;k++)
                {
                    if(rig.BoneForRole(Role(finger+segments[k])) is not int bone)continue;
                    Vector3 direction;
                    if(k<2 && rig.BoneForRole(Role(finger+segments[k+1])) is int next)direction=rest[next].Pos-rest[bone].Pos;
                    else if(k>0 && rig.BoneForRole(Role(finger+segments[k-1])) is int parent)direction=rest[bone].Pos-rest[parent].Pos;
                    else continue;
                    desired[bone]=Quaternion.Normalize(MathQ.FromTo(direction,points[start+k+1]-points[start+k])*rest[bone].Rot);
                    evidence[bone]=JointEvidence.Reconstructed;
                }
            }
            for(var i=0;i<frame.Length;i++)
            {
                var parent=rig.Skeleton[i].ParentIndex;
                var parentRotation=parent<0?Quaternion.Identity:world[parent].Rot;
                if(desired.TryGetValue(i,out var q))frame[i].Rot=Quaternion.Normalize(Quaternion.Inverse(parentRotation)*q);
                world[i]=parent<0?frame[i]:XForm.Compose(world[parent],frame[i]);
            }
        }
        previous=frame;
        Document.Frames.Add(new MotionFrame{Time=time,Positions=frame.Select(x=>MotionDocument.A(x.Pos/100)).ToArray(),
            Rotations=frame.Select(x=>MotionDocument.A(x.Rot)).ToArray(),Evidence=evidence,Confidence=null});
    }
    static Quaternion Basis(Vector3 direction,Vector3 across)
    {
        var x=Vector3.Normalize(direction);var y=across-x*Vector3.Dot(across,x);
        if(y.LengthSquared()<1e-10f)y=MathQ.Perpendicular(x);else y=Vector3.Normalize(y);
        var z=Vector3.Normalize(Vector3.Cross(x,y));
        return Quaternion.CreateFromRotationMatrix(new Matrix4x4(x.X,x.Y,x.Z,0,y.X,y.Y,y.Z,0,z.X,z.Y,z.Z,0,0,0,0,1));
    }
}
